steps:
# Unit Test
- name: 'python:3.7-slim'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install -r a-working/requirements.txt && python ./a-working/unit_tests.py -v'

# Data Validation
- name: 'python:3.7-slim'
  id: Data Validation
  entrypoint: /bin/sh
  args:
  - -c
  - 'python ./a-working/data_validation.py -v'

# # Data Processing
# - name: 'python:3.7-slim'
#   id: Data Processing
#   entrypoint: /bin/sh
#   args:
#   - -c
#   - 'python ./a-working/data_processing.py -v'

# # Model Training
# - name: 'python:3.7-slim'
#   id: Model Training
#   entrypoint: /bin/sh
#   args:
#   - -c
#   - 'python ./a-working/model_training.py -v'

# Point to where the dockerfile is located and build to artifact repository
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/mle-airbus-detection-repository/testing-app:$SHORT_SHA'
  - '-f'
  - '/a-working'
  - '.'

# # This step builds the container image and specifies where to save it
# - name: 'gcr.io/cloud-builders/docker'
#   id: Build To
#   args:
#   - 'build'
#   - '-t'
#   - 'asia-east1-docker.pkg.dev/$PROJECT_ID/mle-airbus-detection-repository/testing-app:$SHORT_SHA'
#   - '.'

# # This step pushes the image to Artifact Registry
# # The PROJECT_ID and SHORT_SHA variables are automatically
# # replaced by Cloud Build.
# - name: 'gcr.io/cloud-builders/docker'
#   id: Push
#   args:
#   - 'push'
#   - 'asia-east1-docker.pkg.dev/$PROJECT_ID/mle-airbus-detection-repository/testing-app:$SHORT_SHA'